# Use postgres/example user/password credentials
version: '3.1'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3333:3333"


volumes:
  database:
